# Generated by Django 6.0.2 on 2026-02-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain_key', models.CharField(max_length=255)),
                ('organization_id', models.CharField(max_length=255)),
                ('subsidiary_id', models.CharField(max_length=255)),
                ('distribution_center_id', models.CharField(max_length=255)),
                ('store_token', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_scraper.store')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app_scraper.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ean', models.CharField(db_index=True, max_length=20)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_offer', models.BooleanField(default=False)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('check_date', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_scraper.store')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_scraper.subcategory')),
            ],
        ),
    ]
